---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: This task will run nosetest
  workspaces:
    - name: source
  params:
    - name: args
      description: nose arguments
      type: string
      default: "-v"
    - name: database_uri
      description: Database connection
      type: string
      default: "sqlite:///test.db"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABSE_URI
          value: $(params.database_uri)
      script: |
        #!/bin/bash
        set -e

        echo "***** Installing dependencies *****"
        python -m pip install --upgrade pip wheel
        pip install -qr requirements.txt

        echo "***** Running nosetests with: $(params.args)"
        nosetests $(params.args)

